import { GoalDef, M, S } from "./types";

// Q2 2026 — Security & Compliance, Revenue Operations, Customer Success, Manager goals
export const goalsPart3: GoalDef[] = [
  // ═══ SECURITY & COMPLIANCE (Q2 2026) ═══
  // Aiden Cooper (idx:24) — high performer
  { idx:501, ownerIdx:24, creatorIdx:6, cycle:"q2_26", parentIdx:554, sharedGroup:"SOC2 Readiness", title:"Reduce mean time to detect security incidents below 15 minutes", desc:"Implement SIEM correlation rules and automated alerting for all critical security events.", thrust:"Threat Detection", meas:M.MIN, unit:"minutes MTTD", start:"45", target:"15", current:"18", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:502, ownerIdx:24, creatorIdx:6, cycle:"q2_26", title:"Achieve 100% endpoint protection coverage", desc:"Deploy EDR agents across all production servers, developer workstations, and CI/CD runners.", thrust:"Endpoint Security", meas:M.MAX, unit:"%", start:"72", target:"100", current:"95", weight:35, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:503, ownerIdx:24, creatorIdx:6, cycle:"q2_26", title:"Complete zero-trust network architecture rollout", desc:"Implement identity-based access controls replacing traditional VPN-based perimeter security.", thrust:"Zero Trust", meas:M.TIMELINE, weight:25, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11", timeline:"2026-06-30" },
  // Hannah Lee (idx:25) — moderate, compliance focus
  { idx:504, ownerIdx:25, creatorIdx:6, cycle:"q2_26", parentIdx:554, sharedGroup:"SOC2 Readiness", title:"Complete SOC2 evidence collection by quarter end", desc:"Gather, organize, and validate all control evidence artifacts required for the Q2 SOC2 audit cycle.", thrust:"Compliance", meas:M.TIMELINE, weight:45, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10", timeline:"2026-06-25" },
  { idx:505, ownerIdx:25, creatorIdx:6, cycle:"q2_26", title:"Reduce compliance audit findings below 3", desc:"Address and close open audit findings from prior SOC2 and internal audit cycles.", thrust:"Governance", meas:M.MIN, unit:"open findings", start:"9", target:"3", current:"5", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11" },
  { idx:506, ownerIdx:25, creatorIdx:6, cycle:"q2_26", title:"Implement GDPR data subject request automation", desc:"Build automated workflow for processing data access, deletion, and portability requests within SLA.", thrust:"Privacy", meas:M.TIMELINE, weight:25, pri:3, status:S.SUBMITTED, subAt:"2026-04-02", timeline:"2026-06-15" },
  // Nathan Scott (idx:26) — stalled
  { idx:507, ownerIdx:26, creatorIdx:6, cycle:"q2_26", sharedGroup:"SOC2 Readiness", title:"Reduce unresolved critical vulnerabilities below 5", desc:"Prioritize and remediate critical CVEs across application layer and third-party dependencies.", thrust:"Vulnerability Management", meas:M.MIN, unit:"critical CVEs", start:"18", target:"5", current:"14", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:508, ownerIdx:26, creatorIdx:6, cycle:"q2_26", title:"Complete red team exercise for production systems", desc:"Execute adversarial simulation testing against production infrastructure and application layer.", thrust:"Security Testing", meas:M.TIMELINE, weight:35, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10", timeline:"2026-05-15" },
  { idx:509, ownerIdx:26, creatorIdx:6, cycle:"q2_26", title:"Implement secrets rotation automation", desc:"Automate rotation of all production secrets, API keys, and certificates on a 90-day cycle.", thrust:"Secret Management", meas:M.MAX, unit:"% secrets auto-rotated", start:"15", target:"90", current:"30", weight:25, pri:3, status:S.DRAFT },
  // Zara Ahmed (idx:27) — good, governance focus
  { idx:510, ownerIdx:27, creatorIdx:6, cycle:"q2_26", title:"Implement vendor risk assessment framework", desc:"Deploy standardized third-party vendor risk evaluation covering security, privacy, and operational resilience.", thrust:"Third-Party Risk", meas:M.MAX, unit:"vendors assessed", start:"5", target:"25", current:"18", weight:35, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11" },
  { idx:511, ownerIdx:27, creatorIdx:6, cycle:"q2_26", title:"Achieve 95% security awareness training completion", desc:"Ensure all employees complete quarterly security awareness training with phishing simulation.", thrust:"Security Culture", meas:M.MAX, unit:"%", start:"68", target:"95", current:"87", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-08", appAt:"2026-04-12" },
  { idx:512, ownerIdx:27, creatorIdx:6, cycle:"q2_26", title:"Establish incident response playbook library", desc:"Document and validate runbooks for the top 15 security incident scenarios.", thrust:"Incident Response", meas:M.MAX, unit:"playbooks completed", start:"3", target:"15", current:"10", weight:35, pri:2, status:S.SUBMITTED, subAt:"2026-04-03" },
  // Marcus Williams (idx:28) — overdue
  { idx:513, ownerIdx:28, creatorIdx:6, cycle:"q2_26", title:"Deploy SIEM log ingestion for all production services", desc:"Ensure all production services emit structured security logs to the centralized SIEM platform.", thrust:"Security Operations", meas:M.MAX, unit:"% services ingesting", start:"40", target:"100", current:"55", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:514, ownerIdx:28, creatorIdx:6, cycle:"q2_26", title:"Reduce false positive alert rate below 10%", desc:"Tune SIEM correlation rules and alert thresholds to reduce analyst alert fatigue.", thrust:"Alert Quality", meas:M.MIN, unit:"%", start:"35", target:"10", current:"28", weight:30, pri:2, status:S.REJECTED, subAt:"2026-04-08", rejAt:"2026-04-12" },
  { idx:515, ownerIdx:28, creatorIdx:6, cycle:"q2_26", title:"Implement 24/7 security monitoring coverage", desc:"Establish around-the-clock SOC monitoring through combination of automation and on-call rotation.", thrust:"SOC Operations", meas:M.TIMELINE, weight:30, pri:2, status:S.SUBMITTED, subAt:"2026-04-14", timeline:"2026-06-01" },

  // ═══ REVENUE OPERATIONS (Q2 2026) ═══
  // Taylor Morrison (idx:29) — moderate
  { idx:516, ownerIdx:29, creatorIdx:7, cycle:"q2_26", parentIdx:555, title:"Increase pipeline conversion rate to 25%", desc:"Optimize sales motion through improved lead scoring and qualification criteria alignment.", thrust:"Sales Efficiency", meas:M.MAX, unit:"%", start:"18", target:"25", current:"21", weight:35, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:517, ownerIdx:29, creatorIdx:7, cycle:"q2_26", title:"Reduce sales cycle length below 45 days", desc:"Streamline proposal-to-close process by implementing automated approval tiers and contract templates.", thrust:"Process Optimization", meas:M.MIN, unit:"days", start:"62", target:"45", current:"54", weight:35, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:518, ownerIdx:29, creatorIdx:7, cycle:"q2_26", title:"Launch territory planning analytics dashboard", desc:"Build interactive territory performance dashboard for regional sales managers.", thrust:"Sales Analytics", meas:M.TIMELINE, weight:30, pri:2, status:S.SUBMITTED, subAt:"2026-04-15", timeline:"2026-06-01" },
  // Jasmine Patel (idx:30) — good performer
  { idx:519, ownerIdx:30, creatorIdx:7, cycle:"q2_26", title:"Improve forecast accuracy to 92%", desc:"Enhance revenue forecasting models with improved weighted pipeline scoring and historical pattern analysis.", thrust:"Forecasting", meas:M.MAX, unit:"%", start:"85", target:"92", current:"89", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:520, ownerIdx:30, creatorIdx:7, cycle:"q2_26", title:"Reduce reporting latency below 2 hours", desc:"Optimize data warehouse refresh cycles and implement real-time materialized views for executive reports.", thrust:"Data Operations", meas:M.MIN, unit:"hours", start:"6", target:"2", current:"3.2", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:521, ownerIdx:30, creatorIdx:7, cycle:"q2_26", title:"Automate monthly revenue reconciliation", desc:"Build automated reconciliation pipeline between CRM bookings and finance actuals.", thrust:"Finance Operations", meas:M.TIMELINE, weight:30, pri:3, status:S.APPROVED, subAt:"2026-04-08", appAt:"2026-04-12", timeline:"2026-05-31" },
  // Brandon Cruz (idx:31) — delayed
  { idx:522, ownerIdx:31, creatorIdx:7, cycle:"q2_26", parentIdx:555, sharedGroup:"Revenue Expansion Initiative", title:"Build predictive churn risk model", desc:"Develop ML-based churn prediction model using product usage, support tickets, and engagement signals.", thrust:"Analytics", meas:M.TIMELINE, weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10", timeline:"2026-05-20" },
  { idx:523, ownerIdx:31, creatorIdx:7, cycle:"q2_26", sharedGroup:"Customer Retention Initiative", title:"Increase enterprise renewal rate to 90%", desc:"Implement proactive renewal engagement playbook triggered by churn risk indicators.", thrust:"Revenue Retention", meas:M.MAX, unit:"%", start:"82", target:"90", current:"84", weight:35, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:524, ownerIdx:31, creatorIdx:7, cycle:"q2_26", title:"Standardize pricing model documentation", desc:"Create and maintain comprehensive pricing model documentation for all product tiers.", thrust:"Pricing Operations", meas:M.TIMELINE, weight:25, pri:3, status:S.REJECTED, subAt:"2026-04-09", rejAt:"2026-04-13" },
  // Rachel Kim (idx:32) — pending
  { idx:525, ownerIdx:32, creatorIdx:7, cycle:"q2_26", title:"Reduce deal desk approval turnaround to 4 hours", desc:"Streamline non-standard deal approval workflows with automated routing and escalation rules.", thrust:"Process Efficiency", meas:M.MIN, unit:"hours", start:"18", target:"4", current:"10", weight:35, pri:1, status:S.SUBMITTED, subAt:"2026-04-12" },
  { idx:526, ownerIdx:32, creatorIdx:7, cycle:"q2_26", title:"Increase CPQ system adoption to 85%", desc:"Drive sales team adoption of configure-price-quote system for all enterprise proposals.", thrust:"Tool Adoption", meas:M.MAX, unit:"%", start:"45", target:"85", current:"58", weight:30, pri:2, status:S.SUBMITTED, subAt:"2026-04-13" },
  { idx:527, ownerIdx:32, creatorIdx:7, cycle:"q2_26", title:"Complete contract template standardization", desc:"Consolidate and standardize enterprise contract templates to reduce legal review cycles.", thrust:"Legal Operations", meas:M.TIMELINE, weight:35, pri:2, status:S.DRAFT },
  // Derek Chen (idx:33) — good
  { idx:528, ownerIdx:33, creatorIdx:7, cycle:"q2_26", title:"Launch executive revenue intelligence dashboard", desc:"Build real-time executive dashboard showing revenue metrics, pipeline health, and forecast variance.", thrust:"Business Intelligence", meas:M.TIMELINE, weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09", timeline:"2026-05-30" },
  { idx:529, ownerIdx:33, creatorIdx:7, cycle:"q2_26", title:"Increase data warehouse query performance by 50%", desc:"Optimize slow queries, add indexes, and implement caching layer for BI dashboard performance.", thrust:"Data Engineering", meas:M.MAX, unit:"% improvement", start:"0", target:"50", current:"38", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:530, ownerIdx:33, creatorIdx:7, cycle:"q2_26", title:"Implement self-service analytics for sales managers", desc:"Deploy self-service reporting tools allowing sales managers to build custom pipeline views.", thrust:"Analytics Enablement", meas:M.MAX, unit:"% managers enabled", start:"10", target:"80", current:"45", weight:30, pri:3, status:S.SUBMITTED, subAt:"2026-04-14" },

  // ═══ CUSTOMER SUCCESS (Q2 2026) ═══
  // Samantha Brooks (idx:34) — high performer
  { idx:531, ownerIdx:34, creatorIdx:8, cycle:"q2_26", parentIdx:556, sharedGroup:"Customer Retention Initiative", title:"Increase enterprise NPS to 55", desc:"Drive NPS improvement through structured QBRs, proactive issue resolution, and executive alignment sessions.", thrust:"Customer Satisfaction", meas:M.MAX, unit:"NPS", start:"42", target:"55", current:"51", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:532, ownerIdx:34, creatorIdx:8, cycle:"q2_26", shared:true, title:"Raise enterprise customer health score to 84", desc:"Improve strategic account health through tightened onboarding checkpoints and executive reviews.", thrust:"Customer Retention", meas:M.MAX, unit:"health score", start:"71", target:"84", current:"80", weight:35, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:533, ownerIdx:34, creatorIdx:8, cycle:"q2_26", title:"Establish customer advisory board program", desc:"Launch quarterly advisory board with top 10 enterprise customers for product feedback.", thrust:"Customer Engagement", meas:M.TIMELINE, weight:25, pri:3, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11", timeline:"2026-06-01" },
  // Kevin Tran (idx:35) — moderate
  { idx:534, ownerIdx:35, creatorIdx:8, cycle:"q2_26", sharedGroup:"Customer Retention Initiative", title:"Reduce enterprise onboarding time to 10 days", desc:"Optimize onboarding playbook with automated provisioning, self-serve training, and milestone tracking.", thrust:"Customer Onboarding", meas:M.MIN, unit:"days", start:"16", target:"10", current:"13", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:535, ownerIdx:35, creatorIdx:8, cycle:"q2_26", title:"Achieve 90% onboarding milestone completion rate", desc:"Ensure all enterprise accounts complete full onboarding checklist within first 30 days.", thrust:"Adoption", meas:M.MAX, unit:"%", start:"72", target:"90", current:"81", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11" },
  { idx:536, ownerIdx:35, creatorIdx:8, cycle:"q2_26", title:"Create self-serve training academy", desc:"Build online training platform with certification tracks for enterprise end users.", thrust:"Education", meas:M.TIMELINE, weight:30, pri:3, status:S.SUBMITTED, subAt:"2026-04-04", timeline:"2026-06-30" },
  // Diana Flores (idx:36) — overdue on renewals
  { idx:537, ownerIdx:36, creatorIdx:8, cycle:"q2_26", sharedGroup:"Customer Retention Initiative", title:"Achieve 92% enterprise renewal rate", desc:"Execute proactive renewal engagement beginning 120 days before contract expiration.", thrust:"Renewal Management", meas:M.MAX, unit:"%", start:"85", target:"92", current:"86", weight:45, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:538, ownerIdx:36, creatorIdx:8, cycle:"q2_26", title:"Reduce involuntary churn below 2%", desc:"Implement payment failure recovery workflows and proactive billing health monitoring.", thrust:"Churn Prevention", meas:M.MIN, unit:"%", start:"5.2", target:"2", current:"4.1", weight:30, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:539, ownerIdx:36, creatorIdx:8, cycle:"q2_26", title:"Launch expansion revenue playbook", desc:"Create systematic upsell/cross-sell playbook triggered by product usage milestones.", thrust:"Revenue Growth", meas:M.TIMELINE, weight:25, pri:2, status:S.REJECTED, subAt:"2026-04-09", rejAt:"2026-04-13" },
  // Chris Anderson (idx:37) — good, technical
  { idx:540, ownerIdx:37, creatorIdx:8, cycle:"q2_26", title:"Resolve priority support escalations within SLA", desc:"Lower average resolution time for P1/P2 escalations from enterprise customers.", thrust:"Service Excellence", meas:M.MIN, unit:"hours", start:"18", target:"8", current:"9.5", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:541, ownerIdx:37, creatorIdx:8, cycle:"q2_26", title:"Implement technical health scoring for all accounts", desc:"Build automated scoring based on API usage patterns, error rates, and feature adoption.", thrust:"Account Intelligence", meas:M.MAX, unit:"accounts scored", start:"8", target:"35", current:"24", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:542, ownerIdx:37, creatorIdx:8, cycle:"q2_26", title:"Build integration troubleshooting knowledge base", desc:"Document resolution steps for top 50 customer integration issues.", thrust:"Knowledge Management", meas:M.MAX, unit:"articles published", start:"10", target:"50", current:"32", weight:30, pri:3, status:S.SUBMITTED, subAt:"2026-04-14" },
  // Priya Singh (idx:38) — stalled
  { idx:543, ownerIdx:38, creatorIdx:8, cycle:"q2_26", title:"Launch customer insights analytics platform", desc:"Build internal analytics platform aggregating product usage, support, and NPS data per account.", thrust:"Customer Analytics", meas:M.TIMELINE, weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10", timeline:"2026-05-30" },
  { idx:544, ownerIdx:38, creatorIdx:8, cycle:"q2_26", title:"Reduce time to generate QBR reports below 2 hours", desc:"Automate data collection and presentation building for quarterly business review decks.", thrust:"Operational Efficiency", meas:M.MIN, unit:"hours", start:"8", target:"2", current:"6", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11" },
  { idx:545, ownerIdx:38, creatorIdx:8, cycle:"q2_26", title:"Map customer journey touchpoints for top 20 accounts", desc:"Document end-to-end customer journey with satisfaction data at each interaction point.", thrust:"Customer Experience", meas:M.MAX, unit:"accounts mapped", start:"0", target:"20", current:"5", weight:30, pri:3, status:S.DRAFT },

  // ═══ MANAGER GOALS (Q2 2026) ═══
  { idx:551, ownerIdx:3, creatorIdx:1, cycle:"q2_26", parentIdx:601, shared:true, title:"Stabilize cross-functional delivery rhythm", desc:"Complete Q2 operating cadence rollout for product, engineering, and customer success teams.", thrust:"Execution Discipline", meas:M.TIMELINE, weight:50, pri:1, status:S.APPROVED, subAt:"2026-04-04", appAt:"2026-04-08", timeline:"2026-06-15" },
  { idx:552, ownerIdx:4, creatorIdx:1, cycle:"q2_26", parentIdx:601, sharedGroup:"Platform Reliability Program", title:"Reduce infrastructure-related customer escalations to zero", desc:"Eliminate customer-visible infrastructure incidents through proactive monitoring and capacity planning.", thrust:"Customer Reliability", meas:M.ZERO, unit:"escalations", start:"5", target:"0", current:"2", weight:50, pri:1, status:S.APPROVED, subAt:"2026-04-04", appAt:"2026-04-08" },
  { idx:553, ownerIdx:5, creatorIdx:1, cycle:"q2_26", parentIdx:603, sharedGroup:"AI Rollout Program", title:"Deliver AI capabilities roadmap for H2 2026", desc:"Define and validate the AI product roadmap with engineering and product stakeholders.", thrust:"Strategic Planning", meas:M.TIMELINE, weight:50, pri:1, status:S.APPROVED, subAt:"2026-04-04", appAt:"2026-04-08", timeline:"2026-06-30" },
  { idx:554, ownerIdx:6, creatorIdx:2, cycle:"q2_26", parentIdx:602, sharedGroup:"SOC2 Readiness", title:"Achieve zero critical compliance gaps", desc:"Close all critical compliance gaps identified in Q1 audit cycle before external audit in Q3.", thrust:"Governance", meas:M.ZERO, unit:"critical gaps", start:"4", target:"0", current:"2", weight:50, pri:1, status:S.APPROVED, subAt:"2026-04-04", appAt:"2026-04-08" },
  { idx:555, ownerIdx:7, creatorIdx:2, cycle:"q2_26", parentIdx:605, sharedGroup:"Revenue Expansion Initiative", title:"Grow net new ARR by 15% quarter-over-quarter", desc:"Drive new logo acquisition and expansion revenue to achieve quarterly ARR growth targets.", thrust:"Revenue Growth", meas:M.MAX, unit:"% QoQ growth", start:"8", target:"15", current:"11", weight:50, pri:1, status:S.APPROVED, subAt:"2026-04-04", appAt:"2026-04-08" },
  { idx:556, ownerIdx:8, creatorIdx:2, cycle:"q2_26", parentIdx:604, sharedGroup:"Customer Retention Initiative", title:"Reduce net revenue churn below 3%", desc:"Implement coordinated retention and expansion strategy to achieve net negative churn.", thrust:"Customer Retention", meas:M.MIN, unit:"%", start:"6.5", target:"3", current:"4.8", weight:50, pri:1, status:S.APPROVED, subAt:"2026-04-04", appAt:"2026-04-08" },
];
