import { GoalDef, M, S } from "./types";

// Executive strategic goals (hierarchy roots) + intentionally flawed goals
export const goalsExecutive: GoalDef[] = [
  // ═══ EXECUTIVE STRATEGIC GOALS (Q2 2026) — hierarchy roots ═══
  { idx:601, ownerIdx:1, creatorIdx:1, cycle:"q2_26", title:"Platform Reliability Initiative", desc:"Drive platform-wide reliability improvements to achieve 99.99% availability and eliminate customer-visible infrastructure incidents across all regions.", thrust:"Strategic Initiative", meas:M.MAX, unit:"% availability", start:"99.9", target:"99.99", current:"99.95", weight:50, pri:1, status:S.APPROVED, subAt:"2026-04-02", appAt:"2026-04-03" },
  { idx:602, ownerIdx:2, creatorIdx:2, cycle:"q2_26", title:"Enterprise Security Readiness", desc:"Achieve enterprise security readiness across SOC2 compliance, vulnerability remediation, and threat detection capabilities before Q3 external audit.", thrust:"Strategic Initiative", meas:M.TIMELINE, weight:50, pri:1, status:S.APPROVED, subAt:"2026-04-02", appAt:"2026-04-03", timeline:"2026-06-30" },
  { idx:603, ownerIdx:1, creatorIdx:1, cycle:"q2_26", title:"AI Product Expansion Program", desc:"Accelerate AI capabilities roadmap to production readiness, including model serving scale, evaluation framework maturity, and enterprise knowledge graph deployment.", thrust:"Strategic Initiative", meas:M.MAX, unit:"% milestones delivered", start:"0", target:"100", current:"62", weight:50, pri:1, status:S.APPROVED, subAt:"2026-04-02", appAt:"2026-04-03" },
  { idx:604, ownerIdx:2, creatorIdx:2, cycle:"q2_26", title:"Customer Retention Excellence", desc:"Reduce net revenue churn and improve enterprise customer health through coordinated onboarding optimization, proactive renewal engagement, and NPS improvement programs.", thrust:"Strategic Initiative", meas:M.MIN, unit:"% net churn", start:"6.5", target:"3", current:"4.8", weight:50, pri:1, status:S.APPROVED, subAt:"2026-04-02", appAt:"2026-04-03" },
  { idx:605, ownerIdx:2, creatorIdx:2, cycle:"q2_26", title:"Revenue Acceleration Initiative", desc:"Drive 15% quarter-over-quarter ARR growth through pipeline optimization, forecast accuracy improvements, and deal velocity acceleration across all enterprise segments.", thrust:"Strategic Initiative", meas:M.MAX, unit:"% QoQ ARR growth", start:"8", target:"15", current:"11", weight:50, pri:1, status:S.APPROVED, subAt:"2026-04-02", appAt:"2026-04-03" },

  // ═══ INTENTIONALLY FLAWED GOALS — enterprise realism ═══
  // Vague, unmeasurable, overloaded — some rejected, some stale drafts
  { idx:611, ownerIdx:23, creatorIdx:23, cycle:"q2_26", title:"Improve AI experience globally", desc:"Make the AI experience better for all users across all products and touchpoints.", thrust:"AI Research", meas:M.MAX, unit:"% improvement", start:"0", target:"100", current:"0", weight:20, pri:3, status:S.REJECTED, subAt:"2026-04-10", rejAt:"2026-04-14" },
  { idx:612, ownerIdx:18, creatorIdx:18, cycle:"q2_26", title:"Make the platform faster", desc:"Improve performance across the entire platform.", thrust:"Infrastructure", meas:M.MAX, unit:"% faster", start:"0", target:"50", current:"0", weight:20, pri:4, status:S.REJECTED, subAt:"2026-04-11", rejAt:"2026-04-15" },
  { idx:613, ownerIdx:28, creatorIdx:28, cycle:"q2_26", title:"Become industry leader in security", desc:"Establish AtomQuest as the recognized industry leader in enterprise SaaS security across all verticals and analyst reports.", thrust:"Security & Compliance", meas:M.MAX, unit:"% industry recognition", start:"0", target:"100", current:"0", weight:15, pri:4, status:S.DRAFT },
  { idx:614, ownerIdx:33, creatorIdx:33, cycle:"q2_26", title:"Optimize everything in the analytics pipeline", desc:"Make all analytics faster, more accurate, and more comprehensive for all stakeholders.", thrust:"Revenue Operations", meas:M.MAX, unit:"% optimization", start:"0", target:"100", current:"5", weight:15, pri:4, status:S.REJECTED, subAt:"2026-04-12", rejAt:"2026-04-16" },
  { idx:615, ownerIdx:35, creatorIdx:35, cycle:"q2_26", title:"Achieve 100% customer satisfaction", desc:"Ensure every single customer interaction results in maximum satisfaction across all channels.", thrust:"Customer Success", meas:M.MAX, unit:"% satisfaction", start:"72", target:"100", current:"72", weight:15, pri:4, status:S.DRAFT },
  { idx:616, ownerIdx:21, creatorIdx:21, cycle:"q2_26", title:"Streamline cross-functional synergies across all departments", desc:"Align all cross-functional workstreams to maximize organizational velocity and minimize friction across every team boundary.", thrust:"AI Research", meas:M.TIMELINE, weight:15, pri:4, status:S.REJECTED, subAt:"2026-04-09", rejAt:"2026-04-14", timeline:"2026-06-30" },
];
