import { GoalDef, M, S } from "./types";

// Q2 2026 — Product Engineering + Infrastructure + AI Research
export const goalsPart2: GoalDef[] = [
  // ═══ PRODUCT ENGINEERING (Q2 2026) ═══
  // Arjun Patel (idx:9) — high performer
  { idx:401, ownerIdx:9, creatorIdx:3, cycle:"q2_26", parentIdx:551, sharedGroup:"Platform Reliability Program", title:"Increase API reliability to 99.95%", desc:"Harden API gateway with circuit breakers, rate limiting, and graceful degradation across all tenant endpoints.", thrust:"Platform Reliability", meas:M.MAX, unit:"%", start:"99.2", target:"99.95", current:"99.8", weight:35, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:402, ownerIdx:9, creatorIdx:3, cycle:"q2_26", title:"Migrate 100% of enterprise tenants to API v3", desc:"Complete the final wave of enterprise tenant migrations from deprecated v2 endpoints.", thrust:"Platform Architecture", meas:M.MAX, unit:"% tenants", start:"65", target:"100", current:"88", weight:35, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:403, ownerIdx:9, creatorIdx:3, cycle:"q2_26", title:"Reduce P95 API response time below 200ms", desc:"Optimize hot-path queries and implement response caching for dashboard aggregation endpoints.", thrust:"Performance", meas:M.MIN, unit:"ms", start:"340", target:"200", current:"245", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11" },
  // Sophia Kim (idx:10) — moderate performer
  { idx:404, ownerIdx:10, creatorIdx:3, cycle:"q2_26", title:"Ship goal cascade visualization feature", desc:"Build interactive goal hierarchy visualization for manager dashboards showing team alignment.", thrust:"Product Innovation", meas:M.TIMELINE, weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-08", appAt:"2026-04-12", timeline:"2026-06-15" },
  { idx:405, ownerIdx:10, creatorIdx:3, cycle:"q2_26", title:"Reduce frontend error rate below 0.5%", desc:"Fix top JavaScript exceptions and implement error boundary coverage for all dashboard components.", thrust:"Quality Engineering", meas:M.MIN, unit:"%", start:"2.1", target:"0.5", current:"1.2", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-09", appAt:"2026-04-13" },
  { idx:406, ownerIdx:10, creatorIdx:3, cycle:"q2_26", title:"Implement accessibility compliance for core flows", desc:"Achieve WCAG 2.1 AA compliance across goal creation, approval, and dashboard workflows.", thrust:"Compliance", meas:M.MAX, unit:"% flows compliant", start:"30", target:"90", current:"55", weight:30, pri:3, status:S.SUBMITTED, subAt:"2026-04-15" },
  // Liam Anderson (idx:11) — delayed contributor
  { idx:407, ownerIdx:11, creatorIdx:3, cycle:"q2_26", title:"Complete multi-tenant data partitioning", desc:"Implement row-level security and tenant-scoped query execution across all database operations.", thrust:"Platform Architecture", meas:M.TIMELINE, weight:45, pri:1, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11", timeline:"2026-05-30" },
  { idx:408, ownerIdx:11, creatorIdx:3, cycle:"q2_26", title:"Reduce database query p99 latency", desc:"Optimize slow queries identified in production profiling, targeting the top 20 worst offenders.", thrust:"Performance", meas:M.MIN, unit:"ms", start:"850", target:"300", current:"620", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-08", appAt:"2026-04-12" },
  { idx:409, ownerIdx:11, creatorIdx:3, cycle:"q2_26", title:"Implement event-driven audit trail system", desc:"Build async event bus for capturing all state transitions with guaranteed delivery.", thrust:"Operational Governance", meas:M.TIMELINE, weight:25, pri:3, status:S.DRAFT },
  // Emma Rodriguez (idx:12) — good completion
  { idx:410, ownerIdx:12, creatorIdx:3, cycle:"q2_26", title:"Redesign manager dashboard experience", desc:"Overhaul manager workspace with real-time team progress, risk indicators, and approval queue.", thrust:"Product Design", meas:M.TIMELINE, weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10", timeline:"2026-06-01" },
  { idx:411, ownerIdx:12, creatorIdx:3, cycle:"q2_26", title:"Increase design system component adoption", desc:"Migrate remaining custom UI components to the shared design system library.", thrust:"Engineering Standards", meas:M.MAX, unit:"% components migrated", start:"45", target:"90", current:"78", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11" },
  { idx:412, ownerIdx:12, creatorIdx:3, cycle:"q2_26", title:"Reduce customer-reported UI defects", desc:"Address top user-reported friction points in goal submission and quarterly update flows.", thrust:"Quality", meas:M.MIN, unit:"open defects", start:"23", target:"5", current:"11", weight:30, pri:2, status:S.SUBMITTED, subAt:"2026-04-14" },
  // Noah Bennett (idx:13) — pending reviews
  { idx:413, ownerIdx:13, creatorIdx:3, cycle:"q2_26", title:"Achieve zero-downtime deployment capability", desc:"Implement blue-green deployment strategy with automated rollback for all production services.", thrust:"DevOps Excellence", meas:M.ZERO, unit:"deployment incidents", start:"4", target:"0", current:"2", weight:40, pri:1, status:S.SUBMITTED, subAt:"2026-04-12" },
  { idx:414, ownerIdx:13, creatorIdx:3, cycle:"q2_26", title:"Reduce build time below 5 minutes", desc:"Optimize CI pipeline through caching, parallelization, and incremental build strategies.", thrust:"Developer Productivity", meas:M.MIN, unit:"minutes", start:"12", target:"5", current:"7", weight:30, pri:2, status:S.SUBMITTED, subAt:"2026-04-13" },
  { idx:415, ownerIdx:13, creatorIdx:3, cycle:"q2_26", title:"Implement infrastructure-as-code for staging environments", desc:"Convert all staging environment provisioning to version-controlled Terraform modules.", thrust:"Automation", meas:M.MAX, unit:"% IaC coverage", start:"20", target:"100", current:"45", weight:30, pri:3, status:S.DRAFT },

  // ═══ INFRASTRUCTURE (Q2 2026) ═══
  // Rohan Mehta (idx:14) — high performer
  { idx:416, ownerIdx:14, creatorIdx:4, cycle:"q2_26", parentIdx:552, sharedGroup:"Platform Reliability Program", title:"Achieve 99.99% platform uptime", desc:"Implement redundancy improvements and automated failover to reach four-nines availability.", thrust:"Reliability", meas:M.MAX, unit:"%", start:"99.9", target:"99.99", current:"99.97", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:417, ownerIdx:14, creatorIdx:4, cycle:"q2_26", title:"Eliminate all Sev-1 production incidents", desc:"Proactively identify and remediate systemic failure modes through chaos engineering and load testing.", thrust:"Incident Prevention", meas:M.ZERO, unit:"Sev-1 incidents", start:"3", target:"0", current:"1", weight:35, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:418, ownerIdx:14, creatorIdx:4, cycle:"q2_26", title:"Deploy observability stack upgrade", desc:"Migrate from legacy monitoring to unified observability platform with distributed tracing.", thrust:"Observability", meas:M.TIMELINE, weight:25, pri:2, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10", timeline:"2026-06-01" },
  // Grace Thompson (idx:15) — moderate
  { idx:419, ownerIdx:15, creatorIdx:4, cycle:"q2_26", title:"Reduce cloud infrastructure cost by 20%", desc:"Right-size compute instances, implement spot instance strategy, and optimize storage tiers.", thrust:"Cost Optimization", meas:M.MIN, unit:"% monthly spend reduction", start:"0", target:"20", current:"12", weight:35, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11" },
  { idx:420, ownerIdx:15, creatorIdx:4, cycle:"q2_26", title:"Complete multi-region failover testing", desc:"Validate automated failover procedures across US-East, US-West, and EU-West regions.", thrust:"Disaster Recovery", meas:M.MAX, unit:"regions validated", start:"0", target:"3", current:"2", weight:35, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:421, ownerIdx:15, creatorIdx:4, cycle:"q2_26", title:"Implement automated capacity planning", desc:"Build predictive capacity planning system based on historical usage patterns and growth projections.", thrust:"Capacity Management", meas:M.TIMELINE, weight:30, pri:3, status:S.SUBMITTED, subAt:"2026-04-14", timeline:"2026-06-15" },
  // Lucas Hall (idx:16) — stalled
  { idx:422, ownerIdx:16, creatorIdx:4, cycle:"q2_26", title:"Migrate legacy databases to managed services", desc:"Move self-managed PostgreSQL and Redis instances to cloud-managed equivalents with zero data loss.", thrust:"Cloud Modernization", meas:M.MAX, unit:"% databases migrated", start:"20", target:"100", current:"35", weight:45, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:423, ownerIdx:16, creatorIdx:4, cycle:"q2_26", title:"Reduce infrastructure drift to zero", desc:"Implement drift detection and automated reconciliation for all Terraform-managed resources.", thrust:"Configuration Management", meas:M.ZERO, unit:"drifted resources", start:"18", target:"0", current:"11", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11" },
  { idx:424, ownerIdx:16, creatorIdx:4, cycle:"q2_26", title:"Standardize container image security scanning", desc:"Integrate vulnerability scanning into all CI pipelines for container image builds.", thrust:"Security", meas:M.MAX, unit:"% pipelines covered", start:"30", target:"100", current:"42", weight:25, pri:3, status:S.DRAFT },
  // Mia Johnson (idx:17) — good completion
  { idx:425, ownerIdx:17, creatorIdx:4, cycle:"q2_26", title:"Increase deployment automation coverage to 95%", desc:"Automate remaining manual deployment steps for all production and staging environments.", thrust:"Automation", meas:M.MAX, unit:"%", start:"70", target:"95", current:"91", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:426, ownerIdx:17, creatorIdx:4, cycle:"q2_26", title:"Implement GitOps workflow for all services", desc:"Adopt ArgoCD-based GitOps for declarative deployment management across all microservices.", thrust:"DevOps", meas:M.MAX, unit:"% services on GitOps", start:"10", target:"80", current:"65", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:427, ownerIdx:17, creatorIdx:4, cycle:"q2_26", title:"Reduce provisioning lead time below 30 minutes", desc:"Automate environment provisioning to enable self-service developer environments.", thrust:"Developer Experience", meas:M.MIN, unit:"minutes", start:"120", target:"30", current:"40", weight:30, pri:3, status:S.SUBMITTED, subAt:"2026-04-15" },
  // James Rivera (idx:18) — overdue
  { idx:428, ownerIdx:18, creatorIdx:4, cycle:"q2_26", title:"Complete network segmentation project", desc:"Implement micro-segmentation across production VPCs to isolate tenant traffic and reduce blast radius.", thrust:"Network Security", meas:M.TIMELINE, weight:45, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09", timeline:"2026-05-01" },
  { idx:429, ownerIdx:18, creatorIdx:4, cycle:"q2_26", title:"Reduce network latency between regions below 50ms", desc:"Optimize inter-region routing and implement edge caching for cross-region API calls.", thrust:"Network Performance", meas:M.MIN, unit:"ms", start:"85", target:"50", current:"72", weight:30, pri:2, status:S.REJECTED, subAt:"2026-04-08", rejAt:"2026-04-12" },
  { idx:430, ownerIdx:18, creatorIdx:4, cycle:"q2_26", title:"Deploy DDoS mitigation for all public endpoints", desc:"Implement WAF rules and rate limiting at edge layer for all customer-facing services.", thrust:"Security", meas:M.TIMELINE, weight:25, pri:2, status:S.SUBMITTED, subAt:"2026-04-14", timeline:"2026-06-10" },

  // ═══ AI RESEARCH (Q2 2026) ═══
  // Ava Wilson (idx:19) — high performer
  { idx:431, ownerIdx:19, creatorIdx:5, cycle:"q2_26", parentIdx:553, sharedGroup:"AI Rollout Program", title:"Increase model evaluation accuracy to 92%", desc:"Improve evaluation pipeline precision through expanded test datasets and cross-validation methodologies.", thrust:"ML Evaluation", meas:M.MAX, unit:"%", start:"83", target:"92", current:"89", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:432, ownerIdx:19, creatorIdx:5, cycle:"q2_26", title:"Launch automated model regression testing", desc:"Build CI-integrated regression testing framework for all production ML models.", thrust:"ML Quality", meas:M.TIMELINE, weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11", timeline:"2026-05-30" },
  { idx:433, ownerIdx:19, creatorIdx:5, cycle:"q2_26", title:"Reduce model training cost per experiment", desc:"Optimize compute utilization through mixed-precision training and spot instance scheduling.", thrust:"Cost Efficiency", meas:M.MIN, unit:"USD per run", start:"450", target:"200", current:"280", weight:30, pri:3, status:S.APPROVED, subAt:"2026-04-08", appAt:"2026-04-12" },
  // David Chang (idx:20) — moderate
  { idx:434, ownerIdx:20, creatorIdx:5, cycle:"q2_26", parentIdx:553, sharedGroup:"AI Rollout Program", title:"Complete enterprise knowledge graph v2", desc:"Expand entity and relationship extraction coverage for enterprise document understanding.", thrust:"NLP Research", meas:M.MAX, unit:"% entity coverage", start:"60", target:"85", current:"72", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10" },
  { idx:435, ownerIdx:20, creatorIdx:5, cycle:"q2_26", title:"Publish internal research findings on retrieval augmentation", desc:"Document and share retrieval-augmented generation findings with engineering and product teams.", thrust:"Knowledge Sharing", meas:M.TIMELINE, weight:25, pri:3, status:S.SUBMITTED, subAt:"2026-04-15", timeline:"2026-06-15" },
  { idx:436, ownerIdx:20, creatorIdx:5, cycle:"q2_26", title:"Improve document classification accuracy", desc:"Enhance multi-label classification model for enterprise document routing and categorization.", thrust:"Model Performance", meas:M.MAX, unit:"% accuracy", start:"78", target:"90", current:"84", weight:35, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11" },
  // Isabella Nguyen (idx:21) — delayed
  { idx:437, ownerIdx:21, creatorIdx:5, cycle:"q2_26", title:"Build A/B testing framework for ML models", desc:"Create infrastructure for online experimentation and statistical significance testing of model variants.", thrust:"ML Infrastructure", meas:M.TIMELINE, weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10", timeline:"2026-05-15" },
  { idx:438, ownerIdx:21, creatorIdx:5, cycle:"q2_26", title:"Reduce data pipeline processing time by 40%", desc:"Optimize ETL pipelines for training data preparation through parallelization and incremental processing.", thrust:"Data Engineering", meas:M.MIN, unit:"hours", start:"6", target:"3.6", current:"5.2", weight:30, pri:2, status:S.APPROVED, subAt:"2026-04-07", appAt:"2026-04-11" },
  { idx:439, ownerIdx:21, creatorIdx:5, cycle:"q2_26", title:"Establish data quality monitoring for training sets", desc:"Implement automated data drift detection and quality scoring for all ML training datasets.", thrust:"Data Quality", meas:M.MAX, unit:"% datasets monitored", start:"10", target:"80", current:"25", weight:30, pri:3, status:S.DRAFT },
  // Ryan Foster (idx:22) — good
  { idx:440, ownerIdx:22, creatorIdx:5, cycle:"q2_26", sharedGroup:"AI Rollout Program", title:"Scale model serving to handle 10K concurrent requests", desc:"Optimize model serving infrastructure with horizontal auto-scaling and request batching.", thrust:"ML Platform", meas:M.MAX, unit:"concurrent requests", start:"2000", target:"10000", current:"7500", weight:40, pri:1, status:S.APPROVED, subAt:"2026-04-05", appAt:"2026-04-09" },
  { idx:441, ownerIdx:22, creatorIdx:5, cycle:"q2_26", title:"Implement model versioning and rollback system", desc:"Build model registry with version tracking, A/B deployment, and one-click rollback capability.", thrust:"ML Ops", meas:M.TIMELINE, weight:35, pri:1, status:S.APPROVED, subAt:"2026-04-06", appAt:"2026-04-10", timeline:"2026-06-01" },
  { idx:442, ownerIdx:22, creatorIdx:5, cycle:"q2_26", title:"Reduce model cold-start time below 5 seconds", desc:"Optimize model loading and warmup procedures for serverless inference endpoints.", thrust:"Performance", meas:M.MIN, unit:"seconds", start:"18", target:"5", current:"8", weight:25, pri:2, status:S.SUBMITTED, subAt:"2026-04-14" },
  // Chloe Martinez (idx:23) — pending
  { idx:443, ownerIdx:23, creatorIdx:5, cycle:"q2_26", title:"Design evaluation rubric for generative AI outputs", desc:"Create comprehensive evaluation methodology for assessing quality of generative model outputs.", thrust:"AI Evaluation", meas:M.TIMELINE, weight:40, pri:1, status:S.SUBMITTED, subAt:"2026-04-12", timeline:"2026-06-01" },
  { idx:444, ownerIdx:23, creatorIdx:5, cycle:"q2_26", title:"Benchmark enterprise LLM against industry standards", desc:"Run standardized benchmarks comparing enterprise LLM performance against GPT-4, Claude, and Gemini baselines.", thrust:"Benchmarking", meas:M.MAX, unit:"% benchmark score", start:"65", target:"85", current:"71", weight:35, pri:1, status:S.SUBMITTED, subAt:"2026-04-13" },
  { idx:445, ownerIdx:23, creatorIdx:5, cycle:"q2_26", title:"Establish human evaluation pipeline for AI quality", desc:"Build internal crowdsourcing platform for systematic human evaluation of AI-generated content.", thrust:"Quality Assurance", meas:M.MAX, unit:"evaluations per week", start:"0", target:"500", current:"120", weight:25, pri:3, status:S.DRAFT },
];
